### ISSUE TITLE
DeepmergeTs

### ISSUE THREAD

**Issue by RebeccaStevens** [loockeeer/deno-deepmerge#1]
Just thought I should let you know that I've now release my [DeepmergeTs](https://github.com/RebeccaStevens/deepmerge-ts) library for deno.

https://deno.land/x/deepmergets

**Comment by loockeeer** [comment]
Oh yes, I saw that! Thanks anyway x) 

 I had created deno deepmerge because I needed a deepmerge and I wanted to test deno.land/x, so no big deal
